### ISSUE TITLE
Can I use AprilBeacon SDK for other iBeacons ?

### ISSUE THREAD

**Issue by niravspaceo** [AprilBrother/AprilBeacon-iOS-SDK#5]
Hello,
 I want to know that whether I can use this SDK for other iBeacon devices or for only April Beacon ?

Regards,
Developer

**Comment by volca** [comment]
Please keep tracking [the link](http://bbs.aprbrother.com/t/can-i-use-aprilbeacon-sdk-for-other-ibeacons/33).
