### ISSUE TITLE
set beacons scan period

### ISSUE THREAD

**Issue by vasiliy1985** [AprilBrother/AprilBeacon-iOS-SDK#6]
Hello!
I use your AprilBeacon-iOS-SDK. To start ranging all April beacons that are visible in range i use the method startRangingBeaconsInRegion: . Then I use delegate method  beaconManager:didRangeBeacons:inRegion:  to retrieve found beacons. This delegate method is calling every 1 second. How can I change this interval, for example if I want to retrieve found beacons more often?
Your SDK for Android has method “public void setForegroundScanPeriod(long scanPeriodMillis, long waitTimeMillis)”. Do you have analogy for iOS SDK?

**Comment by daisysomus** [comment]
SDK for iOS can not change the interval
