### ISSUE TITLE
Battery Level always getting either  100% or 0%

### ISSUE THREAD

**Issue by KiranPatelSpaceo** [AprilBrother/AprilBeacon-iOS-SDK#7]
I am getting batteryLevel either 100% or 0%

I need exactly battery level percentage 
- (void)beaconDidConnected:(ABBeacon *)beaconConnected withError:(NSError *)error
{
    if (error) {
        [self showAlertWithMessage:@"Connection Failed !!"];
        return;
    }
    
    BOOL state = self.beacon.isConnected;

    NSLog(@"Battery Life: %@",beaconConnected.batteryLevel);
   }

**Comment by volca** [comment]
which beacon model do you use?

**Comment by KiranPatelSpaceo** [comment]
NSLog(@"Firmware Revision: %@", beaconConnected.firmwareRevision);
    NSLog(@"Manufacturer Nmae: %@", beaconConnected.manufacturerName);
    NSLog(@"Model Number: %@", beaconConnected.modelNumber);
    NSLog(@"Mac Id: %@",beaconConnected.macAddress);
    NSLog(@"Distance: %f",[beaconConnected.distance floatValue]);
    NSLog(@"Battery Life: %@",beaconConnected.batteryLevel);
    NSLog(@"UUID : %@", [beaconConnected.proximityUUID UUIDString]);



Out put

Firmware Revision: 2.1.2a
Manufacturer Nmae: AprilBrother LLC
Model Number: Model Number
Mac Id: 0xDA486600004C99B4
 Distance: 0.000000
Battery Life: 100
UUID : E2C56DB5-DFFB-48D2-B060-D0F5A71096E0
![img_1201](https://user-images.githubusercontent.com/6309880/37751430-81b907b6-2db8-11e8-94b8-015d25a4fa88.JPG)
![img_1202](https://user-images.githubusercontent.com/6309880/37751431-81f50266-2db8-11e8-9594-cbf3dc4a6b18.JPG)
![img_1203](https://user-images.githubusercontent.com/6309880/37751432-823b789a-2db8-11e8-949a-3fb33ea1d47b.JPG)


Thanks

**Comment by volca** [comment]
It just measure the battery voltage to calculate the battery level. For cell battery, the normal working voltage is 3V. It's hard to get accuracy battery level for the battery.
