### ISSUE TITLE
Newest EEK iBeacon

### ISSUE THREAD

**Issue by tjanela** [AprilBrother/AprilBeacon-iOS-SDK#8]
https://github.com/AprilBrother/AprilBeacon-iOS-SDK/blob/6b558be7052c58e739e8eeb7e33411c95598f435/AprilBeaconDemo/AprilBeaconDemo/ABBluetoothViewController.m#L81

How do I know if I have the "newest EEK iBeacon"?
Updating the firmware exposes this functionality or do I have to purchase a specific beacon? How do I know which one to buy?

@daisysomus 

Thanks in advance.

**Comment by volca** [comment]
You can check the firmware version and hardware version in AprilBeacon.app if connected.

**Comment by tjanela** [comment]
I do have it @volca, this is what reads:
![IMG_5FAD47AB1651-1](https://user-images.githubusercontent.com/223747/183922808-ebf6cfe0-89fb-4dcd-b0f7-3950e034ab23.jpeg)

What values are compatible with having the major, minor, etc.?

**Comment by volca** [comment]
It's the latest beacon model which made at 2020. But the comment in the code is written at 2015.

Do you want to read  battery level when scan iBeacons?

**Comment by tjanela** [comment]
@volca not really, we are interested in Proximity UUID, major, and minor and the "unfiltered" RSSI indicator. 
I'll follow your suggestion and use CB directly to get the advertisement data.

**Comment by volca** [comment]
For ranging beacon, you should use [the method startRangingBeacons(satisfying:)](https://developer.apple.com/documentation/corelocation/cllocationmanager/3240607-startrangingbeacons) in Core Location.

**Comment by tjanela** [comment]
Thanks, @volca, it seems like we should use iOS frameworks directly, if all we want to do is ranging beacons.
Thanks for your inputs.
