### ISSUE TITLE
libAprilBeaconSDK.a does not contain simulator arm64 slices.

### ISSUE THREAD

**Issue by tjanela** [AprilBrother/AprilBeacon-iOS-SDK#9]
@volca  Getting:
ld: in Pods/AprilSDK/AprilSDK/libAprilBeaconSDK.a(ABError.o), building for iOS Simulator, but linking in object file built for iOS, file 'Pods/AprilSDK/AprilSDK/libAprilBeaconSDK.a' for architecture arm64

```
~/AprilSDK ❯❯❯ lipo -archs libAprilBeaconSDK.a
armv7 i386 x86_64 arm64
```

**Comment by volca** [comment]
I suggest using the CoreBluetooth API directly if you just need scan advertisement data. The SDK provide only additional modify feature for AprilBeacon. It's written in 2015 and outdate.

**Comment by tjanela** [comment]
Thanks, @volca.
